FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm config set registry https://registry.yarnpkg.com && \
    npm ci --verbose

# Expose port
EXPOSE 5173

# Start dev server
CMD ["npm", "run", "dev"]
