#!/usr/bin/env python3
"""
Test script to reproduce and verify the attendees bug fix.

Bug: When users change speaker names in verification step (e.g., "Speaker 0" → "Omar"),
the names DO NOT appear in the generated protocol's attendees field.
"""

import sys
import logging
from app.models import Speaker, Protocol, ActionItem, UpdateSpeakersRequest
from app.services.mock_generator import MockGenerator
from app.routers.protocol import _apply_speaker_name_replacements
from app.services.job_manager import JobManager

# Enable detailed logging
logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s - %(name)s - %(message)s'
)
logger = logging.getLogger(__name__)

def print_separator(title=""):
    print("\n" + "=" * 80)
    if title:
        print(f"  {title}")
        print("=" * 80)

def test_scenario_1_empty_confirmed_names():
    """
    SCENARIO 1: Frontend sends speakers with EMPTY confirmedName
    This simulates the bug where frontend doesn't properly send confirmed names.
    """
    print_separator("SCENARIO 1: Empty confirmedName (Bug Simulation)")

    print("\n1. Initial speakers generated by transcription:")
    speakers = [
        Speaker(
            id="speaker-1",
            detectedName="Speaker 0",
            confirmedName=""  # Empty - simulating bug
        ),
        Speaker(
            id="speaker-2",
            detectedName="Speaker 1",
            confirmedName=""
        )
    ]

    for i, s in enumerate(speakers):
        print(f"  Speaker {i}: detected='{s.detected_name}', confirmed='{s.confirmed_name}'")

    print("\n2. Generate protocol with these speakers:")
    mock_gen = MockGenerator()
    protocol = mock_gen.generate_protocol(speakers=speakers)

    print(f"  Attendees: {protocol.attendees}")
    print(f"  Expected: ['Speaker 0', 'Speaker 1'] (since confirmedName is empty)")

    print("\n3. Apply speaker name replacements:")
    result = _apply_speaker_name_replacements(protocol, speakers)

    print(f"  Attendees after replacement: {result.attendees}")
    print(f"  Expected: ['Speaker 0', 'Speaker 1'] (no replacement possible with empty confirmedName)")

    # Verify
    if result.attendees == ['Speaker 0', 'Speaker 1']:
        print("\n✓ PASS: Attendees correctly show detected names when confirmedName is empty")
        return True
    else:
        print(f"\n✗ FAIL: Unexpected attendees: {result.attendees}")
        return False


def test_scenario_2_with_confirmed_names():
    """
    SCENARIO 2: Frontend CORRECTLY sends speakers with confirmedName set
    This simulates the expected happy path.
    """
    print_separator("SCENARIO 2: With confirmedName (Expected Behavior)")

    print("\n1. Speakers with confirmed names (from frontend):")
    speakers = [
        Speaker(
            id="speaker-1",
            detectedName="Speaker 0",
            confirmedName="Omar"  # User confirmed!
        ),
        Speaker(
            id="speaker-2",
            detectedName="Speaker 1",
            confirmedName="Sarah"
        )
    ]

    for i, s in enumerate(speakers):
        print(f"  Speaker {i}: detected='{s.detected_name}', confirmed='{s.confirmed_name}'")

    print("\n2. Generate protocol with these speakers:")
    mock_gen = MockGenerator()
    protocol = mock_gen.generate_protocol(speakers=speakers)

    print(f"  Attendees: {protocol.attendees}")
    print(f"  Expected: ['Omar', 'Sarah'] (using confirmedName)")

    # Verify
    if protocol.attendees == ['Omar', 'Sarah']:
        print("\n✓ PASS: Attendees correctly show confirmed names")
        return True
    else:
        print(f"\n✗ FAIL: Expected ['Omar', 'Sarah'], got {protocol.attendees}")
        return False


def test_scenario_3_full_workflow():
    """
    SCENARIO 3: Full workflow simulation
    - Generate speakers (empty confirmedName)
    - User updates speakers (sets confirmedName)
    - Generate protocol
    """
    print_separator("SCENARIO 3: Full Workflow Simulation")

    print("\n1. Create job and generate initial speakers (transcription phase):")
    job = JobManager.create_job()
    print(f"  Job ID: {job.id}")

    mock_gen = MockGenerator()
    initial_speakers = mock_gen.generate_speakers(count=2)
    print(f"  Generated {len(initial_speakers)} speakers:")
    for i, s in enumerate(initial_speakers):
        print(f"    Speaker {i}: detected='{s.detected_name}', confirmed='{s.confirmed_name}'")

    JobManager.set_speakers(job.id, initial_speakers)

    print("\n2. User updates speaker names (verification phase):")
    updated_speakers = []
    for speaker in initial_speakers:
        # Simulate user confirming names
        updated_speaker = Speaker(
            id=speaker.id,
            detectedName=speaker.detected_name,
            confirmedName="Omar" if speaker.id == "speaker-1" else "Sarah",
            sampleAudioUrl=speaker.sample_audio_url,
            speakingTime=speaker.speaking_time,
            transcriptSnippet=speaker.transcript_snippet,
            confidence=speaker.confidence,
            isExternal=speaker.is_external,
            waveformData=speaker.waveform_data
        )
        updated_speakers.append(updated_speaker)
        print(f"    {speaker.detected_name} → {updated_speaker.confirmed_name}")

    # Simulate PUT /jobs/{id}/speakers
    print("\n3. Update speakers via API (PUT /jobs/{id}/speakers):")
    JobManager.set_speakers(job.id, updated_speakers)
    job = JobManager.get_job(job.id)
    print(f"  Job now has {len(job.speakers)} speakers:")
    for i, s in enumerate(job.speakers):
        print(f"    Speaker {i}: detected='{s.detected_name}', confirmed='{s.confirmed_name}'")

    print("\n4. Generate protocol (POST /jobs/{id}/protocol):")
    protocol = mock_gen.generate_protocol(speakers=job.speakers)
    print(f"  Attendees BEFORE replacement: {protocol.attendees}")

    protocol = _apply_speaker_name_replacements(protocol, job.speakers)
    print(f"  Attendees AFTER replacement: {protocol.attendees}")

    print(f"\n  Executive summary preview:")
    print(f"    {protocol.executive_summary[:100]}...")

    # Verify
    expected_attendees = ['Omar', 'Sarah']
    if protocol.attendees == expected_attendees:
        print(f"\n✓ PASS: Attendees correctly show {expected_attendees}")

        # Also check if names appear in transcript
        if 'Omar' in protocol.full_transcript and 'Sarah' in protocol.full_transcript:
            print("✓ PASS: Confirmed names appear in transcript")
            return True
        else:
            print("✗ FAIL: Confirmed names NOT in transcript")
            return False
    else:
        print(f"\n✗ FAIL: Expected {expected_attendees}, got {protocol.attendees}")
        return False


def test_scenario_4_update_api_payload():
    """
    SCENARIO 4: Test the UpdateSpeakersRequest payload parsing
    Simulates what FastAPI receives from frontend
    """
    print_separator("SCENARIO 4: UpdateSpeakersRequest Parsing")

    print("\n1. Simulate frontend JSON payload:")
    frontend_payload = {
        "speakers": [
            {
                "id": "speaker-1",
                "detectedName": "Speaker 0",
                "confirmedName": "Omar",
                "sampleAudioUrl": "/audio/sample-1.mp3",
                "speakingTime": 245,
                "transcriptSnippet": "Hello everyone...",
                "confidence": 0.85,
                "isExternal": False,
                "waveformData": [0.1, 0.5, 0.3, 0.7]
            },
            {
                "id": "speaker-2",
                "detectedName": "Speaker 1",
                "confirmedName": "Sarah",
                "sampleAudioUrl": "/audio/sample-2.mp3",
                "speakingTime": 180,
                "transcriptSnippet": "I agree with...",
                "confidence": 0.92,
                "isExternal": False,
                "waveformData": [0.2, 0.4, 0.6, 0.8]
            }
        ]
    }

    print(f"  Payload has {len(frontend_payload['speakers'])} speakers")
    for sp_dict in frontend_payload['speakers']:
        print(f"    {sp_dict['id']}: '{sp_dict['detectedName']}' → '{sp_dict['confirmedName']}'")

    print("\n2. Parse with Pydantic (UpdateSpeakersRequest):")
    request = UpdateSpeakersRequest(**frontend_payload)

    print(f"  Parsed {len(request.speakers)} speakers:")
    for i, speaker in enumerate(request.speakers):
        print(f"    Speaker {i}:")
        print(f"      Type: {type(speaker)}")
        print(f"      detected_name: '{speaker.detected_name}'")
        print(f"      confirmed_name: '{speaker.confirmed_name}'")
        print(f"      confirmed_name truthy: {bool(speaker.confirmed_name)}")

    # Verify
    if (request.speakers[0].confirmed_name == "Omar" and
        request.speakers[1].confirmed_name == "Sarah"):
        print("\n✓ PASS: Pydantic correctly parsed confirmedName from camelCase JSON")
        return True
    else:
        print("\n✗ FAIL: Parsing error")
        return False


def main():
    """Run all test scenarios."""
    print("\n" + "╔" + "=" * 78 + "╗")
    print("║" + " " * 20 + "ATTENDEES BUG REPRODUCTION TEST" + " " * 27 + "║")
    print("╚" + "=" * 78 + "╝")

    results = []

    try:
        results.append(("Scenario 1: Empty confirmedName", test_scenario_1_empty_confirmed_names()))
        results.append(("Scenario 2: With confirmedName", test_scenario_2_with_confirmed_names()))
        results.append(("Scenario 3: Full Workflow", test_scenario_3_full_workflow()))
        results.append(("Scenario 4: API Payload Parsing", test_scenario_4_update_api_payload()))
    except Exception as e:
        logger.exception("Test failed with exception")
        results.append(("Exception", False))

    # Summary
    print_separator("TEST SUMMARY")
    passed = sum(1 for _, result in results if result)
    total = len(results)

    for name, result in results:
        status = "✓ PASS" if result else "✗ FAIL"
        print(f"  {status}: {name}")

    print(f"\n  Total: {passed}/{total} passed")

    if passed == total:
        print("\n  🎉 ALL TESTS PASSED!")
        return 0
    else:
        print(f"\n  ⚠️  {total - passed} TEST(S) FAILED")
        return 1


if __name__ == "__main__":
    sys.exit(main())
